--- #YAML:1.0
name:               DR-TarantoolQueue
version:            0.12
abstract:           client for tarantool's queue
author:
    - Dmitry E. Oboukhov <unera@debian.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:           0
    Coro:           0
    DR::Tarantool:  0
    JSON::XS:       0
    Mouse:          0
resources:
    bugtracker:  https://github.com/mailru/tarantool-queue/issues
    homepage:    https://github.com/mailru/tarantool-queue
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
